apiVersion: v1
kind: Service
metadata:
  name: wsrestsecurity
  namespace: dev
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:887482798966:certificate/09aad7f2-3ce4-4630-9646-f9c11437f458
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  type: LoadBalancer    
  selector:
    app: wsrestsecurity
