apiVersion: v1
kind: Service
metadata:
  name: wsrestsecurity
  namespace: dev
spec:
  ports:
    - name: http
      port: 3000
    - name: https
      port: 443
  type: LoadBalancer    
  selector:
    app: wsrestsecurity